# Generated by Django 3.0.3 on 2020-08-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(1, 'Men'), (2, 'Women')], default=1)),
                ('card_no', models.CharField(max_length=18)),
            ],
        ),
    ]
