# Generated by Django 3.0.3 on 2020-08-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='Sex')),
            ],
        ),
    ]
