# Generated by Django 3.0.3 on 2020-08-07 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': '地址', 'verbose_name_plural': '地址'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': '饭店', 'verbose_name_plural': '饭店'},
        ),
        migrations.AlterModelOptions(
            name='waiter',
            options={'verbose_name': '服务员', 'verbose_name_plural': '服务员'},
        ),
        migrations.AddField(
            model_name='waiter',
            name='sex',
            field=models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=128, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=64, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=128, verbose_name='店名'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_learning.Place', verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_hot_dogs',
            field=models.BooleanField(default=False, verbose_name='售卖热狗'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='serves_pizza',
            field=models.BooleanField(default=False, verbose_name='售卖Pizza'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='name',
            field=models.CharField(max_length=128, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_learning.Restaurant', verbose_name='所属饭店'),
        ),
    ]
