# Generated by Django 3.0.3 on 2020-08-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_learning', '0002_auto_20200808_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
    ]
